#!/usr/bin/env bash
# devflow/lib/skills.sh — devflow skills implementation
# Manages skills: list, install, remove, convert.
#
# Layout (since registry v2.0.0):
#   skills/<name>/SKILL.md  — folder-based skills, one per name
#   skills/registry.json    — metadata (category, layer, description) per skill
#
# `devflow skills install <name>` copies skills/<name>/ to <project>/.claude/skills/<name>/.
# `devflow skills convert` delegates to scripts/build-skills.sh + build-flows.sh — the single
#   generator that renders the plugin copies from the source of truth (skills/<name>/SKILL.md).

SKILLS_TARGET_DIR=".claude/skills"

devflow_skills() {
  local action="${1:-list}"
  shift || true

  case "$action" in
    list)    skills_list ;;
    install) skills_install "$@" ;;
    remove)  skills_remove "$@" ;;
    convert) skills_convert "$@" ;;
    *)       die "Unknown skills action: $action. Use: list, install, remove, convert" ;;
  esac
}

skills_registry() {
  local root
  root="$(devflow_root)"
  local registry="${root}/skills/registry.json"

  if [[ ! -f "$registry" ]]; then
    die "Skills registry not found: $registry"
  fi
  echo "$registry"
}

skills_list() {
  local registry
  registry="$(skills_registry)"

  section "Available skills"

  if ! has_cmd jq; then
    die "jq is required for skills management. Install with: brew install jq"
  fi

  local count
  count=$(jq '.skills | length' "$registry")

  if [[ "$count" -eq 0 ]]; then
    info "No skills registered."
    return 0
  fi

  jq -r '.skills[] | "\(.name)\t\(.description // "No description")\t\(.category // "")"' "$registry" | while IFS=$'\t' read -r name desc category; do
    printf "  ${BOLD}%-25s${RESET} %s\n" "$name" "$desc"

    # Mark as installed if folder-based skill exists in current project
    local proj
    proj="$(project_root 2>/dev/null || echo "")"
    if [[ -n "$proj" && -f "${proj}/${SKILLS_TARGET_DIR}/${name}/SKILL.md" ]]; then
      printf "  %-25s %s\n" "" "(installed)"
    fi
  done

  echo ""
}

skills_install() {
  local name="${1:-}"
  [[ -z "$name" ]] && die "Usage: devflow skills install <name>"

  local root proj
  root="$(devflow_root)"
  proj="$(project_root)"

  if ! has_cmd jq; then
    die "jq is required for skills management. Install with: brew install jq"
  fi

  # Validate skill exists in registry
  local registry
  registry="$(skills_registry)"
  local registered
  registered=$(jq -r --arg n "$name" '.skills[] | select(.name == $n) | .name' "$registry")

  if [[ -z "$registered" ]]; then
    die "Skill not found in registry: $name"
  fi

  local source_dir="${root}/skills/${name}"
  if [[ ! -f "${source_dir}/SKILL.md" ]]; then
    die "Skill source missing: ${source_dir}/SKILL.md"
  fi

  local target="${proj}/${SKILLS_TARGET_DIR}/${name}"
  mkdir -p "$(dirname "$target")"

  if [[ -d "$target" ]]; then
    rm -rf "$target"
  fi
  cp -R "$source_dir" "$target"

  ok "Installed skill '${name}' to ${SKILLS_TARGET_DIR}/${name}"
}

skills_remove() {
  local name="${1:-}"
  [[ -z "$name" ]] && die "Usage: devflow skills remove <name>"

  local proj
  proj="$(project_root)"
  local target="${proj}/${SKILLS_TARGET_DIR}/${name}"

  if [[ ! -d "$target" ]]; then
    die "Skill '${name}' is not installed in this project."
  fi

  rm -rf "$target"
  ok "Removed skill '${name}' from ${SKILLS_TARGET_DIR}/${name}"
}

# ── Convert: transform devflow skills into a Claude Code plugin ──────────────
#
# Each skill is emitted twice into the plugin:
#   - devflow-plugin/skills/<name>/SKILL.md   (folder-based, agent-invokable via Skill tool)
#   - devflow-plugin/commands/<name>.md       (flat slash-command mirror, `name:` field stripped)
# The plugin.json `skills` array lists every SKILL.md so all skills are loaded.

skills_convert() {
  # The single source of truth is skills/<name>/SKILL.md. The plugin copies
  # (devflow-plugin/{skills,commands}), the plugin.json skills array, and the flows are
  # GENERATED by scripts/build-skills.sh + scripts/build-flows.sh (also `make skills-sync`).
  # This subcommand now just runs those generators so old muscle-memory / docs keep working.
  local output=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --output) output="$2"; shift 2 ;;
      --name) warn "devflow skills convert: --name is a no-op now (plugin name lives in plugin.json)"; shift 2 ;;
      --marketplace) warn "devflow skills convert: --marketplace is a no-op now (marketplace.json is static; edit in place)"; shift ;;
      --prune) warn "devflow skills convert: --prune is a no-op now (build-skills.sh always removes copies with no source)"; shift ;;
      *) die "Unknown option: $1. Usage: devflow skills convert [--output <dir>]" ;;
    esac
  done

  local root; root="$(devflow_root)"
  has_cmd jq || die "jq is required for skills conversion. Install with: brew install jq"

  section "Regenerating the devflow plugin from the single source (skills/<name>/SKILL.md)"
  if [[ -n "$output" ]]; then
    info "Output: ${output} (skills + commands + plugin.json; flows target the real plugin only)"
    DEVFLOW_PLUGIN_OUT="$output" bash "${root}/scripts/build-skills.sh"
  else
    bash "${root}/scripts/build-skills.sh"
    bash "${root}/scripts/build-flows.sh"
  fi
  ok "Plugin regenerated. marketplace.json / hooks.json / .mcp.json are static; edit them in place."
}
